name: gas_ahorro
publish_to: "none"
description: App para ver precios de gasolineras en tiempo real.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  http: ^1.2.2
  url_launcher: ^6.3.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/map_style_dark.json
    - assets/icon/logo.png
    - assets/splash/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/logo.png
  adaptive_icon_background: "#0B3A2B"
  adaptive_icon_foreground: assets/icon/logo.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#0B3A2B"
  image: assets/splash/splash.png
  android: true
  ios: true
  android_12:
    color: "#0B3A2B"
    image: assets/splash/splash.png
