name: gas_ahorro
publish_to: "none"
description: App para ver precios de gasolineras en tiempo real.
version: 1.0.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  http: ^1.6.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/map_style_dark.json
    - assets/icon/logo.png
    - assets/splash/splash.png
    - assets/splash/splash_background.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/logo.png
  image_path_ios: assets/icon/logo_ios.png
  adaptive_icon_background: "#0B3A2B"
  adaptive_icon_foreground: assets/icon/logo_android_foreground.png
  remove_alpha_ios: false

flutter_native_splash:
  color: "#0B3A2B"
  android: true
  ios: true
  android_12:
    color: "#0B3A2B"
